### ISSUE TITLE
Highlighting current day as well as another random day...

### ISSUE THREAD

**Issue by AseemWangoo** [mennorenkens/flutter_scrolling_calendar#1]
Hello all,

This plugin is great!!!...I noticed one issue that it highlights current day as well as a random day( mostly 3-4 days earlier date)...

e.g If today is 3rd April, then it highlights 30th March as well.. 

Kindly look into the matter...Attaching sample screenshot
![Simulator Screen Shot - iPhone X - 2019-04-03 at 16 59 42](https://user-images.githubusercontent.com/16626254/56221039-0bc2ef00-609c-11e9-8430-27ceb4b0ca62.png)

**Comment by zepfietje** [comment]
I am unable to reproduce this issue.
@AseemWangoo could you try to reproduce this bug on the latest [develop](https://github.com/mennorenkens/flutter_scrolling_calendar/commits/develop) branch?
f917373cf3c0c9fe0c656758fa3db94477095cd3 introduced a new way to check if the date is today and possibly fixed this issue.
