### ISSUE TITLE
A RenderFlex overflowed by 40 pixels on the right.

### ISSUE THREAD

**Issue by pcg92** [mennorenkens/flutter_scrolling_calendar#3]
In a lot of devices the calendar widget raise the overflow error.

**Comment by zepfietje** [comment]
@pcegarra could you provide some specific device info and display resolution? Also, screenshots would help.

**Comment by pcg92** [comment]
Hi, for example:
Pocophone F1
1080 x 2246 pixels
![índice](https://user-images.githubusercontent.com/10808022/60951259-0b33a080-a2f9-11e9-8a64-cf9b99ff0e58.jpg)

**Comment by pcg92** [comment]
I have changed the `(width < 400)` instead 340 for ScreenSizes.small, seems better, Im going to try with more devices, like iphones

**Comment by zepfietje** [comment]
400 is indeed the right value. This has been fixed in 45a6eceb9ec1c61cb41102c5d6d4bb70d1bf3f02.
