### ISSUE TITLE
Bottom Pixel overflow

### ISSUE THREAD

**Issue by MobileMon** [mennorenkens/flutter_scrolling_calendar#5]
![Simulator Screen Shot - iPhone 11 - 2019-12-13 at 20 44 27](https://user-images.githubusercontent.com/2768159/70841613-db2d8380-1de9-11ea-8b5f-32dc3e96e546.png)

How can I fix this? I'm new to Flutter. This is a great control btw

**Comment by mennorenkens** [comment]
The overflow doesn't really seem to have major impact. It won't be visible in release mode. Cannot fix it myself for now unfortunately.
