### ISSUE TITLE
A RenderFlex overflowed by 1.0 pixels on the bottom on each year on real device

### ISSUE THREAD

**Issue by kaitoriu** [mennorenkens/flutter_scrolling_calendar#7]
![IMG-0454](https://user-images.githubusercontent.com/2552398/77935722-07f3a100-72dc-11ea-828a-5300744fe48c.PNG)
Hi, I like your project and I using it in my project. But I have a problem, when I use your calendar in emulator it's works fine, but when I try in my iphone 11 device it show A RenderFlex overflowed by 1.0 pixels on the bottom on each year. I hope you can fix it. Thank you very much

**Comment by zepfietje** [comment]
Hi @kaitoriu 👋
This issue has been reported before. However, as we're no longer actively using this package ourselves, we can't find the time to fix it. Feel free to create a pull request!

**Comment by mennorenkens** [comment]
@kaitoriu I agreed with @zepfietje. 
Suddenly had some time however, and it should be fixed now!

**Comment by kaitoriu** [comment]
Thank you very much @mennorenkens, this calendar is very helpful for me.
