### ISSUE TITLE
How to change the text color for month names

### ISSUE THREAD

**Issue by krishnakumarcn** [mennorenkens/flutter_scrolling_calendar#8]

**Comment by zepfietje** [comment]
Hi @krishnakumarcn 👋
Customizing the text color of month titles is currently not supported.
However, it shouldn't be too difficult to implement, so feel free to create a pull request!

**Comment by krishnakumarcn** [comment]
[PR#9](https://github.com/mennorenkens/flutter_scrolling_calendar/pull/9)

**Comment by zepfietje** [comment]
@krishnakumarcn, a new version including customizable month title styling has just been released.

Thanks for taking the time to implement the feature!
